[pytest]
minversion = 7.0
addopts = --cov=src --cov-report term-missing
pythonpath = src
testpaths = tests
env = 
    BYGGESAGER_POSTGRES_DB_HOST=None
    BYGGESAGER_POSTGRES_DB_USER=None
    BYGGESAGER_POSTGRES_DB_PASS=None
    BYGGESAGER_POSTGRES_DB_DATABASE=None
    BYGGESAGER_POSTGRES_DB_PORT=None
